sonar.projectKey=revisium_revo-tui
sonar.organization=revisium
sonar.projectName=revo-tui
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,.scannerwork/**,.sonar/**,pnpm-lock.yaml
